#!/bin/bash
bundle exec passenger start --rackup app.ru \
--engine builtin --disable-turbocaching --disable-security-update-check \
--spawn-method direct --min-instances 8 --max-pool-size 8 --max-request-queue-size 1024 \
--address 0.0.0.0 --port 9292 --environment production --daemonize
